version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patientdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./patient-tracking-api
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=patientdb;Username=postgres;Password=postgres
    depends_on:
      - db

  ui:
    build:
      context: ./patient-ui
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  db-data:
